version: '3'

services:
  db:
   image: mysql:5.7
   restart: always
   ports:
    - "3306:3306"
   expose:
      - '3306'
   environment:
    MYSQL_DATABASE: ${DB_NAME}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   container_name: teslodb
   volumes: 
    - ./mysql:/var/lib/mysql